application:
  name: waitlisted-hasura
  project: waitlisted
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "11.7"
  name: waitlisted-database
routers:
- name: main
  routes:
  - application_name: waitlisted-hasura
    paths:
    - /*
